### ISSUE TITLE
Building from synce4l-0.9.0 tarball fails

### ISSUE THREAD

**Issue by mlichvar** [intel/synce4l#14]
The Makefile uses a git command to get a version string to be printed by the -v option. This command fails when building from the released tarball if not unpacked in a subdirectory of a git repository (in which case the version string is wrong).

Maybe the command could be expanded to check for the `.git` directory and fall back to a hardcoded version string, which could be update before each release?

**Comment by mmichaliINTC** [comment]
Yes - that is a great catch. We definitely need to fill this gap.
Much thanks @mlichvar for pointing us this problem.
I'm leaving this issue open till we solve it.

**Comment by mlichvar** [comment]
Yes, that looks good to me. Thanks.

**Comment by mmichaliINTC** [comment]
0.9.1 is released with the fix, should be working fine now.
Thanks!
