### ISSUE TITLE
How to set module_name and clock_id?

### ISSUE THREAD

**Issue by Shihta** [intel/synce4l#58]
Hi,

I'm using Intel E810-XXVDA4T, and want to start the dpll monitor.
however from https://github.com/intel/synce4l/blob/main/synce_dev.c#L814, it requires to set module_name and clock_id but I don't know what are them in my system.

here is my cgu screenshot and my time source is GNSS:
![截圖 2024-10-02 下午4 19 49](https://github.com/user-attachments/assets/b102a68b-416a-41b3-b755-cc1ba372ddc8)

could you help me to find my module_name and clock_id?

Thanks!

**Comment by kubalewski** [comment]
Hi @Shihta !

Sorry but I am not sure what exactly you mean with "start the dpll monitor" part.
Could you please elaborate on that?

In general synce4l is Synchronous Ethernet daemon, thus dpll monitoring is part of it's internal functionality.

module_name and clock_id are both required when the one is trying to run synce4l based on Linux DPLL subsystem - please verify if your kernel/ice driver do support this:
$ genl-ctrl-list | grep dpll
0x0014 dpll version 1

For ice driver (out of tree) it shall work on latest released version https://github.com/intel/ethernet-linux-ice/releases/tag/v1.15.4 

### module_name
module_name is name of kernel module driving the EEC dpll in Linux DPLL Subsystem.
In case of E810-XXVDA4T:
**module_name ice**

### clock_id
clock_id is in case of Intel NIC's a serial number (taken from PF0 pci slot: <dev bus id>.<dev slot it>.0):
**$ sudo lspci -s 21:00.0 -vv | grep "Device Serial Number"**
        Capabilities: [150 v1] Device Serial Number 40-a6-b7-ff-ff-72-cc-68

The clock id is simply Device Serial Number without dashes.
Convert it to decimal if hex value would not work:
40-a6-b7-ff-ff-72-cc-68 -> **0x40a6b7ffff72cc68** -> **4658613174691613800**

i.e.:
**clock_id 4658613174691613800**


### Alternative using Linux DPLL subsystem
The other way would be to simply query the Linux DPLL subsystem to find a dpll device, where those values are simply provided.

A helper script from Linux kernel source code repository allows to query DPLL subsystem:
**$ ./tools/net/ynl/cli.py --spec Documentation/netlink/specs/dpll.yaml --dump device-get**
[{'clock-id': 4658613174691613800,
  'id': 8,
  **'lock-status': 'locked-ho-acq',**
  'mode': 'automatic',
  'mode-supported': ['automatic'],
  **'module-name': 'ice',**
  'type': 'eec'},
 {'clock-id': 4658613174691613800,
  'id': 9,
  'lock-status': 'locked-ho-acq',
  'mode': 'automatic',
  'mode-supported': ['automatic'],
  'module-name': 'ice',
  'type': 'pps'}]


Hope that helps!

BR,
Arkadiusz

**Comment by Shihta** [comment]
Hi @kubalewski 

Thank you very much for your detailed explanation!
I mainly want to understand how the code is written for monitoring the dpll status, so I have this question.

However, after following your tutorial, I encountered a problem.
After executing genl-ctrl-list, I did not see the dpll information, as shown in the figure below:
![截圖 2024-10-02 下午6 49 29](https://github.com/user-attachments/assets/90e47388-d3aa-47d2-9cad-72a048bc81c4)


Here is the version information and screenshots that may be useful:
ice: 1.14.11
NVM: 4.50
kernel: 5.15.0-1052-realtime
libnl: 3.5.0-0.1
OS: ubuntu 22.04
![截圖 2024-10-02 下午6 50 56](https://github.com/user-attachments/assets/ac0d93ed-df0a-42ff-9566-373d8c583fb9)


I would like your help to identify what the possible problem is.
On the other hand, I want to know what problems will occur when running synce4l without dpll support?

Thank you!

**Comment by kubalewski** [comment]
Unfortunately, this means you do not have a support for DPLL built into your kernel.
You could either:
- rebuild the kernel for officially released (kernel.org) 6.7 (or later), as there was DPLL subsystem introduced,
- use distribution which included the DPLL enablement (i.e., RH OCP/9, CentOS Stream 9, probably some others but need to ask distribution vendor if they do support it).

The synce4l can work without the DPLL subsystem (so called legacy mode) where the user provides system command to enable/disable given source and get dpll state. Config example here: https://github.com/intel/synce4l/blob/main/configs/synce4l.cfg 

The legacy mode was left mostly for older Out Of Tree drivers and kernels without DPLL support, as it is only required to provide few commands and simply enable Synchronous Ethernet.

Hope that help!

BR,
Arkadiusz
