### ISSUE TITLE
sync4l.cfg not up to date

### ISSUE THREAD

**Issue by KarimH22** [intel/synce4l#6]
Hello
the file synce4l.cfg is not up-to-date with last driver, indeed

eec_get_state_cmd		cat /sys/class/net/enp1s0f0/device/cgu_state
shall be replaced by
eec_get_state_cmd		cat /sys/class/net/enp1s0f0/device/dpll_0_state
thank you

BR
Kar

**Comment by mmichaliINTC** [comment]
Hello @KarimH22,

Much thanks for contacting us. `synce4l` is hardware-agnostic opensource application and should not be tied to any particular vendor/hardware. This config file is just an example, don't aim to be up to date with Intel NICs releases - but we can make this change for the convenience of E810T users (early adopters). I'm leaving this issue open till the proposed change reaches the main branch.

Again - we really appreciate you taking care of that config file - thanks.

Have a wonderful day!
M^2

**Comment by mmichaliINTC** [comment]
Hi,

The updated `cfg/synce4l` is in main.

All the best,
M^2
